import PlusnewAbstractElement from '@plusnew/core/src/PlusnewAbstractElement';
import type { htmlElement } from './dom/htmlElement';
import type { linkElement } from './dom/linkElement';
import type { metaElement } from './dom/metaElement';
import type { styleElement } from './dom/styleElement';
import type { titleElement } from './dom/titleElement';
import type { bodyElement } from './dom/bodyElement';
import type { headElement } from './dom/headElement';
import type { addressElement } from './dom/addressElement';
import type { articleElement } from './dom/articleElement';
import type { asideElement } from './dom/asideElement';
import type { footerElement } from './dom/footerElement';
import type { headerElement } from './dom/headerElement';
import type { h1Element } from './dom/h1Element';
import type { h2Element } from './dom/h2Element';
import type { h3Element } from './dom/h3Element';
import type { h4Element } from './dom/h4Element';
import type { h5Element } from './dom/h5Element';
import type { h6Element } from './dom/h6Element';
import type { hgroupElement } from './dom/hgroupElement';
import type { mainElement } from './dom/mainElement';
import type { navElement } from './dom/navElement';
import type { sectionElement } from './dom/sectionElement';
import type { blockquoteElement } from './dom/blockquoteElement';
import type { ddElement } from './dom/ddElement';
import type { dirElement } from './dom/dirElement';
import type { divElement } from './dom/divElement';
import type { dlElement } from './dom/dlElement';
import type { dtElement } from './dom/dtElement';
import type { figcaptionElement } from './dom/figcaptionElement';
import type { figureElement } from './dom/figureElement';
import type { hrElement } from './dom/hrElement';
import type { liElement } from './dom/liElement';
import type { olElement } from './dom/olElement';
import type { pElement } from './dom/pElement';
import type { preElement } from './dom/preElement';
import type { ulElement } from './dom/ulElement';
import type { aElement } from './dom/aElement';
import type { abbrElement } from './dom/abbrElement';
import type { bElement } from './dom/bElement';
import type { bdiElement } from './dom/bdiElement';
import type { bdoElement } from './dom/bdoElement';
import type { brElement } from './dom/brElement';
import type { citeElement } from './dom/citeElement';
import type { codeElement } from './dom/codeElement';
import type { dataElement } from './dom/dataElement';
import type { dfnElement } from './dom/dfnElement';
import type { emElement } from './dom/emElement';
import type { iElement } from './dom/iElement';
import type { kbdElement } from './dom/kbdElement';
import type { markElement } from './dom/markElement';
import type { qElement } from './dom/qElement';
import type { rbElement } from './dom/rbElement';
import type { rpElement } from './dom/rpElement';
import type { rtElement } from './dom/rtElement';
import type { rtcElement } from './dom/rtcElement';
import type { rubyElement } from './dom/rubyElement';
import type { sElement } from './dom/sElement';
import type { sampElement } from './dom/sampElement';
import type { smallElement } from './dom/smallElement';
import type { spanElement } from './dom/spanElement';
import type { strongElement } from './dom/strongElement';
import type { subElement } from './dom/subElement';
import type { supElement } from './dom/supElement';
import type { timeElement } from './dom/timeElement';
import type { ttElement } from './dom/ttElement';
import type { uElement } from './dom/uElement';
import type { varElement } from './dom/varElement';
import type { wbrElement } from './dom/wbrElement';
import type { areaElement } from './dom/areaElement';
import type { audioElement } from './dom/audioElement';
import type { imgElement } from './dom/imgElement';
import type { mapElement } from './dom/mapElement';
import type { trackElement } from './dom/trackElement';
import type { videoElement } from './dom/videoElement';
import type { appletElement } from './dom/appletElement';
import type { embedElement } from './dom/embedElement';
import type { iframeElement } from './dom/iframeElement';
import type { noembedElement } from './dom/noembedElement';
import type { objectElement } from './dom/objectElement';
import type { paramElement } from './dom/paramElement';
import type { pictureElement } from './dom/pictureElement';
import type { sourceElement } from './dom/sourceElement';
import type { canvasElement } from './dom/canvasElement';
import type { noscriptElement } from './dom/noscriptElement';
import type { scriptElement } from './dom/scriptElement';
import type { delElement } from './dom/delElement';
import type { insElement } from './dom/insElement';
import type { captionElement } from './dom/captionElement';
import type { colElement } from './dom/colElement';
import type { colgroupElement } from './dom/colgroupElement';
import type { tableElement } from './dom/tableElement';
import type { tbodyElement } from './dom/tbodyElement';
import type { tdElement } from './dom/tdElement';
import type { tfootElement } from './dom/tfootElement';
import type { thElement } from './dom/thElement';
import type { theadElement } from './dom/theadElement';
import type { trElement } from './dom/trElement';
import type { buttonElement } from './dom/buttonElement';
import type { datalistElement } from './dom/datalistElement';
import type { fieldsetElement } from './dom/fieldsetElement';
import type { formElement } from './dom/formElement';
import type { inputElement } from './dom/inputElement';
import type { labelElement } from './dom/labelElement';
import type { legendElement } from './dom/legendElement';
import type { meterElement } from './dom/meterElement';
import type { optgroupElement } from './dom/optgroupElement';
import type { optionElement } from './dom/optionElement';
import type { outputElement } from './dom/outputElement';
import type { progressElement } from './dom/progressElement';
import type { selectElement } from './dom/selectElement';
import type { textareaElement } from './dom/textareaElement';
import type { detailsElement } from './dom/detailsElement';
import type { dialogElement } from './dom/dialogElement';
import type { menuElement } from './dom/menuElement';
import type { menuitemElement } from './dom/menuitemElement';
import type { summaryElement } from './dom/summaryElement';
import type { contentElement } from './dom/contentElement';
import type { elementElement } from './dom/elementElement';
import type { shadowElement } from './dom/shadowElement';
import type { slotElement } from './dom/slotElement';
import type { templateElement } from './dom/templateElement';
import type { altGlyphElement } from './dom/altGlyphElement';
import type { altGlyphDefElement } from './dom/altGlyphDefElement';
import type { altGlyphItemElement } from './dom/altGlyphItemElement';
import type { animateElement } from './dom/animateElement';
import type { animateColorElement } from './dom/animateColorElement';
import type { animateMotionElement } from './dom/animateMotionElement';
import type { animateTransformElement } from './dom/animateTransformElement';
import type { circleElement } from './dom/circleElement';
import type { clipPathElement } from './dom/clipPathElement';
import type { colorprofileElement } from './dom/colorprofileElement';
import type { cursorElement } from './dom/cursorElement';
import type { defsElement } from './dom/defsElement';
import type { descElement } from './dom/descElement';
import type { ellipseElement } from './dom/ellipseElement';
import type { feBlendElement } from './dom/feBlendElement';
import type { feDropShadowElement } from './dom/feDropShadowElement';
import type { feColorMatrixElement } from './dom/feColorMatrixElement';
import type { feComponentTransferElement } from './dom/feComponentTransferElement';
import type { feCompositeElement } from './dom/feCompositeElement';
import type { feConvolveMatrixElement } from './dom/feConvolveMatrixElement';
import type { feDiffuseLightingElement } from './dom/feDiffuseLightingElement';
import type { feDisplacementMapElement } from './dom/feDisplacementMapElement';
import type { feDistantLightElement } from './dom/feDistantLightElement';
import type { feFloodElement } from './dom/feFloodElement';
import type { feFuncAElement } from './dom/feFuncAElement';
import type { feFuncBElement } from './dom/feFuncBElement';
import type { feFuncGElement } from './dom/feFuncGElement';
import type { feFuncRElement } from './dom/feFuncRElement';
import type { feGaussianBlurElement } from './dom/feGaussianBlurElement';
import type { feImageElement } from './dom/feImageElement';
import type { feMergeElement } from './dom/feMergeElement';
import type { feMergeNodeElement } from './dom/feMergeNodeElement';
import type { feMorphologyElement } from './dom/feMorphologyElement';
import type { feOffsetElement } from './dom/feOffsetElement';
import type { fePointLightElement } from './dom/fePointLightElement';
import type { feSpecularLightingElement } from './dom/feSpecularLightingElement';
import type { feSpotLightElement } from './dom/feSpotLightElement';
import type { feTileElement } from './dom/feTileElement';
import type { feTurbulenceElement } from './dom/feTurbulenceElement';
import type { filterElement } from './dom/filterElement';
import type { fontElement } from './dom/fontElement';
import type { fontfaceElement } from './dom/fontfaceElement';
import type { fontfaceFormatElement } from './dom/fontfaceFormatElement';
import type { fontfaceNameElement } from './dom/fontfaceNameElement';
import type { fontfaceSrcElement } from './dom/fontfaceSrcElement';
import type { fontfaceUriElement } from './dom/fontfaceUriElement';
import type { foreignObjectElement } from './dom/foreignObjectElement';
import type { gElement } from './dom/gElement';
import type { glyphElement } from './dom/glyphElement';
import type { glyphRefElement } from './dom/glyphRefElement';
import type { hkernElement } from './dom/hkernElement';
import type { imageElement } from './dom/imageElement';
import type { lineElement } from './dom/lineElement';
import type { linearGradientElement } from './dom/linearGradientElement';
import type { markerElement } from './dom/markerElement';
import type { maskElement } from './dom/maskElement';
import type { metadataElement } from './dom/metadataElement';
import type { missingglyphElement } from './dom/missingglyphElement';
import type { mpathElement } from './dom/mpathElement';
import type { pathElement } from './dom/pathElement';
import type { patternElement } from './dom/patternElement';
import type { polygonElement } from './dom/polygonElement';
import type { polylineElement } from './dom/polylineElement';
import type { radialGradientElement } from './dom/radialGradientElement';
import type { rectElement } from './dom/rectElement';
import type { setElement } from './dom/setElement';
import type { stopElement } from './dom/stopElement';
import type { svgElement } from './dom/svgElement';
import type { switchElement } from './dom/switchElement';
import type { symbolElement } from './dom/symbolElement';
import type { textElement } from './dom/textElement';
import type { textPathElement } from './dom/textPathElement';
import type { trefElement } from './dom/trefElement';
import type { tspanElement } from './dom/tspanElement';
import type { useElement } from './dom/useElement';
import type { viewElement } from './dom/viewElement';
import type { vkernElement } from './dom/vkernElement';

declare global {
  namespace plusnew {
    namespace JSX {
      /**
       * the JSX.Element is a abstract representation of a Component
       */
      interface Element extends PlusnewAbstractElement {}

      interface ElementChildrenAttribute {
        // @FIXME children are always arrays, but typescript doesn't accept that because of react
        children: {};
      }

      /**
       * All the DOM Nodes are here
       */
      interface IntrinsicElements {
        html: htmlElement;
        link: linkElement;
        meta: metaElement;
        style: styleElement;
        title: titleElement;
        body: bodyElement;
        head: headElement;
        address: addressElement;
        article: articleElement;
        aside: asideElement;
        footer: footerElement;
        header: headerElement;
        h1: h1Element;
        h2: h2Element;
        h3: h3Element;
        h4: h4Element;
        h5: h5Element;
        h6: h6Element;
        hgroup: hgroupElement;
        main: mainElement;
        nav: navElement;
        section: sectionElement;
        blockquote: blockquoteElement;
        dd: ddElement;
        dir: dirElement;
        div: divElement;
        dl: dlElement;
        dt: dtElement;
        figcaption: figcaptionElement;
        figure: figureElement;
        hr: hrElement;
        li: liElement;
        ol: olElement;
        p: pElement;
        pre: preElement;
        ul: ulElement;
        a: aElement;
        abbr: abbrElement;
        b: bElement;
        bdi: bdiElement;
        bdo: bdoElement;
        br: brElement;
        cite: citeElement;
        code: codeElement;
        data: dataElement;
        dfn: dfnElement;
        em: emElement;
        i: iElement;
        kbd: kbdElement;
        mark: markElement;
        q: qElement;
        rb: rbElement;
        rp: rpElement;
        rt: rtElement;
        rtc: rtcElement;
        ruby: rubyElement;
        s: sElement;
        samp: sampElement;
        small: smallElement;
        span: spanElement;
        strong: strongElement;
        sub: subElement;
        sup: supElement;
        time: timeElement;
        tt: ttElement;
        u: uElement;
        var: varElement;
        wbr: wbrElement;
        area: areaElement;
        audio: audioElement;
        img: imgElement;
        map: mapElement;
        track: trackElement;
        video: videoElement;
        applet: appletElement;
        embed: embedElement;
        iframe: iframeElement;
        noembed: noembedElement;
        object: objectElement;
        param: paramElement;
        picture: pictureElement;
        source: sourceElement;
        canvas: canvasElement;
        noscript: noscriptElement;
        script: scriptElement;
        del: delElement;
        ins: insElement;
        caption: captionElement;
        col: colElement;
        colgroup: colgroupElement;
        table: tableElement;
        tbody: tbodyElement;
        td: tdElement;
        tfoot: tfootElement;
        th: thElement;
        thead: theadElement;
        tr: trElement;
        button: buttonElement;
        datalist: datalistElement;
        fieldset: fieldsetElement;
        form: formElement;
        input: inputElement;
        label: labelElement;
        legend: legendElement;
        meter: meterElement;
        optgroup: optgroupElement;
        option: optionElement;
        output: outputElement;
        progress: progressElement;
        select: selectElement;
        textarea: textareaElement;
        details: detailsElement;
        dialog: dialogElement;
        menu: menuElement;
        menuitem: menuitemElement;
        summary: summaryElement;
        content: contentElement;
        element: elementElement;
        shadow: shadowElement;
        slot: slotElement;
        template: templateElement;

        altGlyph: altGlyphElement;
        altGlyphDef: altGlyphDefElement;
        altGlyphItem: altGlyphItemElement;
        animate: animateElement;
        animateColor: animateColorElement;
        animateMotion: animateMotionElement;
        animateTransform: animateTransformElement;
        circle: circleElement;
        clipPath: clipPathElement;
        colorprofile: colorprofileElement;
        cursor: cursorElement;
        defs: defsElement;
        desc: descElement;
        ellipse: ellipseElement;
        feBlend: feBlendElement;
        feColorMatrix: feColorMatrixElement;
        feComponentTransfer: feComponentTransferElement;
        feComposite: feCompositeElement;
        feConvolveMatrix: feConvolveMatrixElement;
        feDiffuseLighting: feDiffuseLightingElement;
        feDisplacementMap: feDisplacementMapElement;
        feDistantLight: feDistantLightElement;
        feDropShadow: feDropShadowElement;
        feFlood: feFloodElement;
        feFuncA: feFuncAElement;
        feFuncB: feFuncBElement;
        feFuncG: feFuncGElement;
        feFuncR: feFuncRElement;
        feGaussianBlur: feGaussianBlurElement;
        feImage: feImageElement;
        feMerge: feMergeElement;
        feMergeNode: feMergeNodeElement;
        feMorphology: feMorphologyElement;
        feOffset: feOffsetElement;
        fePointLight: fePointLightElement;
        feSpecularLighting: feSpecularLightingElement;
        feSpotLight: feSpotLightElement;
        feTile: feTileElement;
        feTurbulence: feTurbulenceElement;
        filter: filterElement;
        font: fontElement;
        fontface: fontfaceElement;
        'fontface-format': fontfaceFormatElement;
        'fontface-name': fontfaceNameElement;
        'fontface-src': fontfaceSrcElement;
        'fontface-uri': fontfaceUriElement;
        foreignObject: foreignObjectElement;
        g: gElement;
        glyph: glyphElement;
        glyphRef: glyphRefElement;
        hkern: hkernElement;
        image: imageElement;
        line: lineElement;
        linearGradient: linearGradientElement;
        marker: markerElement;
        mask: maskElement;
        metadata: metadataElement;
        missingglyph: missingglyphElement;
        mpath: mpathElement;
        path: pathElement;
        pattern: patternElement;
        polygon: polygonElement;
        polyline: polylineElement;
        radialGradient: radialGradientElement;
        rect: rectElement;
        set: setElement;
        stop: stopElement;
        svg: svgElement;
        switch: switchElement;
        symbol: symbolElement;
        text: textElement;
        textPath: textPathElement;
        tref: trefElement;
        tspan: tspanElement;
        use: useElement;
        view: viewElement;
        vkern: vkernElement;
      }

      interface IntrinsicAttributes {
        key?: string | number;
      }
    }
  }
}
